services:
  db:
    image: postgres
    restart: always
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: chat-app
      POSTGRES_DB: chat-app
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "63798:6379"
    volumes:
      - cache:/data
 
volumes:
  pgdata:
  cache:
    driver: local